### ISSUE TITLE
Managing shared user environments

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/bridge-data-platform#11]
### Summary

[**Note:** "shared" here means each user gets an identical computing environment, not that they can communicate/share data etc with each other.]

The researchers will probably want a range of languages and packages available in order to perform their analyses. One way to manage this could be by having an "environment" repo which contains [repo2docker configuration files](https://repo2docker.readthedocs.io/en/latest/config_files.html). A CI pipeline would then use repo2docker to build an image (the benefit of using repo2docker is that it will install the servers required for Jupyter Notebooks, Lab and RStudio to work on the Hub) and push it to a registry. JupyterHub could then pull this image as the user environment whenever a new server is spun up. Adding a new dependency then becomes as "easy" as merging a PR to the environment repo, which users could do themselves.

Instructions on how to integrate repo2docker in CI can be found here: https://repo2docker.readthedocs.io/en/latest/howto/deploy.html

**Why use Docker Hub instead of an Azure Container Registry?**

Cheaper 😄

### TODO

- [x] Create an "environment" repo
  - https://github.com/alan-turing-institute/bridge-data-environment
- [x] Create a corresponding repository on Docker Hub (under turinginst org?)
  - https://hub.docker.com/repository/docker/turinginst/bridge-data-env/general
- [x] Configure Travis or other CI vendor to use repo2docker to build the environment and push to Docker Hub
- [ ] Configure JupyterHub to pull the environment image for new users
  - There is a script for comparing the tags on the JupyterHub to those on Docker Hub in #40. The Pull Request to change these in `config-template.yaml` will need to be written manually.
  - An attempt to automate this process is ongoing in #35

**Comment by sgibson91** [comment]
I don't think this process will be as easy to automate as I first envisioned, so I'm closing this issue for now.
