### ISSUE TITLE
Deploy a JupyterHub on Kubernetes

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/bridge-data-platform#2]
### Task

Deploy a JupyterHub on Kubernetes following the [Zero to JupyterHub on Kubernetes guide](https://zero-to-jupyterhub-k8s.readthedocs.io/index.html)

### TODO

- [x] Get Service Principal from IT
- [x] Deploy Kubernetes cluster
- [x] Configure Helm (PR #4 )
- [ ] Install JupyterHub (PR #5 )
- [x] Update CD pipeline to connect to the Azure resources and perform upgrades as necessary
