### ISSUE TITLE
TODO / ROADMAP

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/bridge-data-platform#58]
### 1. Turing IT

- [ ] Chase IT to add the bridge-data.turing.ac.uk domain to their Named Server Records. Ticket number C2002-202.

### 2. HTTPS Encryption

- [ ] Use cert-manager to automatically issue certificates for the cluster internet endpoints. Issue #7. Documentation at https://alan-turing-institute.github.io/hub23-deploy on cert-manager may come in useful.
  - :warning: May not be applicable if we move to JupyterHub-on-Hadoop (https://github.com/alan-turing-institute/bridge-data-platform/issues/12#issuecomment-611573592)

### 3. Azure Active Directory Authentication

- [ ] Ask IT/Warwick to edit the AD auth app with the new domain name and implement authentication via our Turing AD tenancy. Issue #25. Ticket number C2003-134 (may have missing client secret?)

### 4. Collaboration with Autodesk

- [ ] Complete request to grant Jacky access to Azure subscription `1bab529c-d5c8-4ce2-be26-fe341066bfcd`. Ticket number I2004-285.
- [ ] Autodesk to deploy their infrastructure to the subscription. Issue #12.
- [ ] Connect the JupyterHub and 360 platforms. Issue #10.
  - ⚠️ This may involve switching to JupyterHub-on-Hadoop.

### 5. Processes for allowing access to the data

- Possibly involving a TopDesk ticket where a data agreement is signed and IT create an account for the researcher which we can add to the [user whitelist](https://github.com/alan-turing-institute/bridge-data-platform/blob/5e27d152a32c3b0d2d25e73202a51140d8fea4e1/config/config-template.yaml#L11-L13)

### 6. Restricting access based on IP address

- JupyterHub can restrict inbound traffic to only a whitelist of IP addresses. Before Covid, this would have been the main IP addresses for the partner universities. In the current climate, two options could be to either not implement this or to ask for the IP address during the data access request process. Issue #9
