### ISSUE TITLE
Enable HTTPS with Let's Encrypt

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/bridge-data-platform#7]
### Summary

We should secure our connection via HTTPS. We can achieve this by requesting certificates from [Let's Encrypt](https://letsencrypt.org/) and we can do it automatically by using a service such as [cert-manager](https://cert-manager.io/docs/).

[JupyterHub does support Let's Encrypt](https://zero-to-jupyterhub-k8s.readthedocs.io/advanced.html#ingress-and-automatic-https-with-kube-lego-let-s-encrypt) but it uses [kube-lego](https://www.jetstack.io/open-source/kube-lego/), but this service is [deprecated, and will no longer be available after June 2020](https://github.com/jetstack/kube-lego#kube-lego). JupyterHub [do have plans to migrate to cert-manager](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/475), but it's unclear when that will be.

### TODO

- [x] Get a subdomain from Turing IT
  - ~~Ticket open: C2002-202~~
  - Ticket (re)opened: I2008-385
- [x] Set up A record for Hub external IP to the subdomain
- [ ] ~~Install new helm charts~~
  - ~~[nginx-ingress](https://github.com/kubernetes/ingress-nginx): allows us to use a load balancer and monitor the ingress ports~~
  - ~~[cert-manager](https://github.com/jetstack/cert-manager): will automatically request new certificates 30 days before expiry~~
  - EDIT 11.09.20: JupyterHub has instructions for automatically setting up HTTPS [here](https://zero-to-jupyterhub.readthedocs.io/en/0.9.0/administrator/security.html) we can use
- [x] Update GitHub OAuth2 application with domain name and `https`
- [x] Update JupyterHub config file with domain name and `https`
- [x] Update Continuous Deployment pipeline
  - Remove templating of IP address
  - ~~Upgrade cert-manager deployment if/when necessary~~ (no longer needed as per above edit)

**Comment by annahadji** [comment]
Upgraded to latest versions of Helm and JupyterHub. Latest stable commit with automatic https encryption using LetsEncrypt, `e16f86f1567c2aa5177e3d71190e9e5d02e0b840`.
