### ISSUE TITLE
Authenticate access to the Hub using GitHub

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/bridge-data-platform#8]
### Summary

For the time being, we want to be able to restrict who can log onto the Hub and access the data. We can achieve this by authenticating against a third party, such as GitHub (Docs: https://zero-to-jupyterhub-k8s.readthedocs.io/authentication.html#github). We can then collect a whitelist of users we expect to be using the Hub who are granted access.

### TODO

- [x] Create a GitHub OAuth application
- [x] Add Client ID and Secret values to the Key Vault
- [x] Update the JupyterHub config to enable authentication
- [x] Update the Azure Pipeline to template the config
- [x] Add @sgibson91 and @edaub as admins
- [ ] Develop a procedure allowing researchers to request to be put on the whitelist
